# Generated by Django 5.1.4 on 2024-12-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updateData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('website', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, default='', max_length=800)),
            ],
        ),
        migrations.DeleteModel(
            name='UpdateData1',
        ),
    ]
